### ISSUE TITLE
Kallisto Bustools "Failed to find compatible kallisto binary."

### ISSUE THREAD

**Issue by SimoniMD** [basilkhuder/Seurat-to-RNA-Velocity#17]
Hi! Thanks for this tutorial.

I'm stuck at the first part of the tutorial. I've managed to get the .gtf and .fa, and this is my code, but i'm getting an error with kb-bustools

`kb ref -i index.idx -g t2g.txt -f1 cdna.fa -f2 intron.fa -c1 cdna_t2c.txt -c2 intron_t2c.txt --workflow lamanno -n 4 Homo_sapiens.GRCh38.cdna.all.fa Homo_sapiens.GRCh38.104.gtf`

and my error generated is:
`Traceback (most recent call last):
  File "/home/simonim/anaconda2/envs/kb/bin/kb", line 8, in <module>
    sys.exit(main())
  File "/home/simonim/anaconda2/envs/kb/lib/python3.8/site-packages/ngs_tools/logging.py", line 62, in inner
    return func(*args, **kwargs)
  File "/home/simonim/anaconda2/envs/kb/lib/python3.8/site-packages/kb_python/main.py", line 1346, in main
    raise UnsupportedOSError(
kb_python.config.UnsupportedOSError: Failed to find compatible kallisto binary. Provide a compatible binary with the `--kallisto` option or run `kb compile`.`

I thought this had something to do with the file path, but I'm running the command in the same folder as the .fa and .gtf, and have played around with that with no success. any thoughts?

**Comment by SimoniMD** [comment]
Nevermind, figured it out!

**Comment by Jiangmeling** [comment]
Hello, I have the same problem as above. How do you solve it?
