### ISSUE TITLE
high unspliced counts by velocyto

### ISSUE THREAD

**Issue by rtoddler** [basilkhuder/Seurat-to-RNA-Velocity#2]
Hi, 
Thank you for your incredible guideline. I had a problem making loom file by velocyto. Here is the code I use: 

**velocyto run -b filtered_barcodes.tsv -o velocyto_output -m mm10_repeats_repeatMasker.gtf  possorted_genome_bam.bam refdata-cellranger-GRCh38-3.0.0/genes/genes.gtf**

I can successfully generate the loom file but the unspliced RNA is very high (unspliced:spliced=0.92:0.08). This is not expected since the dataset is generated from 10X 3' v3.1 single-cell library. Do you have any idea why I am getting this ratio?

I wonder if I used the wrong input for velocyto. Here are what I use:
1. barcodes.tsv: unzipped file from CellRanger outs>filtered_feature_bc_matrix>barcodes.gz
2. repeatMasker.gtf: downloaded from [USCS table browser](https://genome.ucsc.edu/cgi-bin/hgTables?hgsid=611454127_NtvlaW6xBSIRYJEBI0iRDEWisITa&clade=mammal&org=Mouse&db=mm10&hgta_group=allTracks&hgta_track=rmsk&hgta_table=0&hgta_regionType=genome&position=chr12%3A56%2C694%2C976-56%2C714%2C605&hgta_outputType=gff&hgta_outFileName=hg38_repeats_repeatMasker_allTracks.gtf)
3. bam file: file from CellRanger outs>possorted_genome_bam.bam
4. genes.gtf: mm10 mouse reference dataset provided by 10x

Any comment will be appreciated!

**Comment by basilkhuder** [comment]
Hi there! 

Are you using a human GTF file (refdata-cellranger-GRCh38-3.0.0/genes/genes.gtf) or was that a mistake in typing?

**Comment by rtoddler** [comment]
Thank you for your speedy response! I'm sorry. That was a mistake. I use mm10

**Comment by basilkhuder** [comment]
Gotcha - thanks for clarifying. You're right though, the unspliced proportion is uncannily high. There doesn't seem to be anything wrong with the input commands, so the only suggestion I have is trying to re-run this without the repeat-masker file and see what proportions arise. If that doesn't change anything, you might want to try talking to the [velocyto team](https://github.com/velocyto-team/velocyto.py/issues) (although, issues on their Github haven't been getting many replies as of late.)

**Comment by rtoddler** [comment]
Good to know! Yes, I will try to run it without repeat-masker. You are right...I browsed through ALL the issues on velocyto-team github and could not find the answers. I'm sooo glad that I find your tutorial (especially the part for extracting filtered cell ID). Once I figure out the loom file, I would definitely give it a shot. Might come back here for more questions tho because I'm really new to RNA velocity analysis.

Thank you again! Your guide is very clear and helpful.
