### ISSUE TITLE
Fail to filter loom by CellID extracted from Seurat

### ISSUE THREAD

**Issue by rtoddler** [basilkhuder/Seurat-to-RNA-Velocity#4]
Hi,
I have problem when trying to filter loom with CellID extracted from Seurat object.
1. When I import the loom file by **sample = anndata.read_loom("sample.loom")**, I get this warning message: _ariable names are not unique. To make them unique, call `.var_names_make_unique`_. Do I need to run **sample.var_names_make_unique()**?
2. If I ignore the warning in the above question and continue to load CellID_obs.cvs and filter by **sample = sample[sample[np.isin(sample.obs.index,cellID_obs[0])]]**, I get the following error:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/.local/lib/python3.6/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2890             try:
-> 2891                 return self._engine.get_loc(casted_key)
   2892             except KeyError as err:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 0

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
<ipython-input-18-2d8dcb94b58c> in <module>
----> 1 sample = sample[sample[np.isin(sample.obs.index,cellID_obs[0])]]

~/.local/lib/python3.6/site-packages/pandas/core/frame.py in __getitem__(self, key)
   2900             if self.columns.nlevels > 1:
   2901                 return self._getitem_multilevel(key)
-> 2902             indexer = self.columns.get_loc(key)
   2903             if is_integer(indexer):
   2904                 indexer = [indexer]

~/.local/lib/python3.6/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2891                 return self._engine.get_loc(casted_key)
   2892             except KeyError as err:
-> 2893                 raise KeyError(key) from err
   2894 
   2895         if tolerance is not None:

KeyError: 0 

Could you help me with this?
Thank you so much!

**Comment by JingleW** [comment]
I met the same problem. 
1. After running "run sample.var_names_make_unique()", there was no warning message: ariable names are not unique. 
2. However, when I running sample = sample[sample[np.isin(sample.obs.index,cellID_obs[0])]], the same error occurred. It seems that the "sample_one.obs.index" in the loom file cannot match the "cellID_obs".  I got my cellID_obs.csv of one sample from a Seurat object composed of multiple single-cell samples. 
Thank you. @basilkhuder

**Comment by basilkhuder** [comment]
Hi to both of you! 

If you could, please open up your cell observation file (either in excel or python) and look to see the name of the column that has the ids. Use this name for subsetting the loom file (so if the column is named "x"): 

```python
sample[sample[np.isin(sample.obs.index,cellID_obs["x"])]]
```

Thanks!

**Comment by basilkhuder** [comment]
> 1. When I import the loom file by **sample = anndata.read_loom("sample.loom")**, I get this warning message: _ariable names are not unique. To make them unique, call `.var_names_make_unique`_. Do I need to run **sample.var_names_make_unique()**?

Go ahead and make them unique. Check [this out](https://github.com/theislab/anndata/issues/344) for more information.

**Comment by rtoddler** [comment]
> Hi to both of you!
> 
> If you could, please open up your cell observation file (either in excel or python) and look to see the name of the column that has the ids. Use this name for subsetting the loom file (so if the column is named "x"):
> 
> ```python
> sample[sample[np.isin(sample.obs.index,cellID_obs["x"])]]
> ```
> 
> Thanks!

**Hi, 
I have thought about that as well but I got another error (see below.) I wonder if it is because the format of indexes are different in sample.obs.index and cellID_obs.
For exapmel, in cellID_obs, the index is listed as "AAACCCAAGTATGGCG-1" whereas in sample.obs.index, it's "AAACCCAAGTATGGCGx".**

IndexError                                Traceback (most recent call last)
<ipython-input-9-f37c6da70937> in <module>
----> 1 sample = sample[sample[np.isin(sample.obs.index,cellID_obs["x"])]]

~/.local/lib/python3.6/site-packages/anndata/_core/anndata.py in __getitem__(self, index)
   1085     def __getitem__(self, index: Index) -> "AnnData":
   1086         """Returns a sliced view of the object."""
-> 1087         oidx, vidx = self._normalize_indices(index)
   1088         return AnnData(self, oidx=oidx, vidx=vidx, asview=True)
   1089 

~/.local/lib/python3.6/site-packages/anndata/_core/anndata.py in _normalize_indices(self, index)
   1066 
   1067     def _normalize_indices(self, index: Optional[Index]) -> Tuple[slice, slice]:
-> 1068         return _normalize_indices(index, self.obs_names, self.var_names)
   1069 
   1070     # TODO: this is not quite complete...

~/.local/lib/python3.6/site-packages/anndata/_core/index.py in _normalize_indices(index, names0, names1)
     32             index = index[0].values, index[1]
     33     ax0, ax1 = unpack_index(index)
---> 34     ax0 = _normalize_index(ax0, names0)
     35     ax1 = _normalize_index(ax1, names1)
     36     return ax0, ax1

~/.local/lib/python3.6/site-packages/anndata/_core/index.py in _normalize_index(indexer, index)
    104             return positions  # np.ndarray[int]
    105     else:
--> 106         raise IndexError(f"Unknown indexer {indexer!r} of type {type(indexer)}")
    107 
    108 

IndexError: Unknown indexer View of AnnData object with n_obs × n_vars = 0 × 32285
    var: 'Accession', 'Chromosome', 'End', 'Start', 'Strand'
    layers: 'matrix', 'ambiguous', 'spliced', 'unspliced' of type <class 'anndata._core.anndata.AnnData'>

**Comment by JingleW** [comment]
Hi, thanks very much for all the replies.
First, I modified the cellID_obs manually, and the modified cellID_obs is shown below. 
![image](https://user-images.githubusercontent.com/59153414/96668954-d97c0700-138e-11eb-880f-25d5dd7bccb5.png)
And my sample_one.obs.index is shown below. 
![image](https://user-images.githubusercontent.com/59153414/96669082-13e5a400-138f-11eb-9314-4dc9ce34a34b.png)
Then I tried different ways for the script "sample_one = sample_one[sample_one[np.isin(sample_one.obs.index,sample_obs["x"])]]".
1. sample_one = sample_one[sample_one[np.isin(sample_one.obs.index,cellID_obs["x"])]]
![image](https://user-images.githubusercontent.com/59153414/96669167-3e376180-138f-11eb-82f2-15c3e07b2280.png)

2. sample_one = sample_one[sample_one[np.isin(sample_one.obs.index,cellID_obs["y"])]]
![image](https://user-images.githubusercontent.com/59153414/96669201-59a26c80-138f-11eb-9792-6333eae79c1d.png)

3. sample_one = sample_one[sample_one[np.isin(sample_one.obs.index,cellID_obs["z"])]]
![image](https://user-images.githubusercontent.com/59153414/96669280-7e96df80-138f-11eb-9b34-f46046c583a9.png)


It seemed the filtering worked when cellID_obs were totally the same as the sample_one.obs.index. However, an index error still happened? Have I missed something or any script was wrong?

**Comment by basilkhuder** [comment]
Just realized the typo. It should be: 

```python
sample[np.isin(sample.obs.index,cellID_obs["x"])]
```

**Comment by JingleW** [comment]
> Just realized the typo. It should be:
> 
> ```python
> sample[np.isin(sample.obs.index,cellID_obs["x"])]
> ```
> 
> _Edit: In your case, I'm guessing "z" would be the column name._

Yes, sample_one = sample_one[np.isin(sample_one.obs.index,cellID_obs["z"])] worked. 
Thank you.

**Comment by rtoddler** [comment]
Thank you all for the suggesitons.
@JingleW  How did you modify your CellID.cvs? Mine only has the first two columns (unamed 0 and x).

**Comment by rtoddler** [comment]
Hi all,
Thank you so much for the suggestions. I modified the CellID.csv as JingleW suggested and ran _sample[np.isin(sample.obs.index,cellID_obs["x"])]_. The problem has been resolved!

**Comment by AAA-3** [comment]
> > 1. When I import the loom file by **sample = anndata.read_loom("sample.loom")**, I get this warning message: _ariable names are not unique. To make them unique, call `.var_names_make_unique`_. Do I need to run **sample.var_names_make_unique()**?
> 
> Go ahead and make them unique. Check [this out](https://github.com/theislab/anndata/issues/344) for more information.

Hello everyone! First time user of bioinformatics tools and curious to why would we want the variable names to be unique? According to [this AnnData page](https://anndata.readthedocs.io/en/latest/anndata.read_loom.html?highlight=cellid), the variable names are genes ... if more than one cell is expressing a gene, would we not expect repeats? And would it not be more relevant for us to make the obs_names unique since that holds our CellIDs? I had simillar issues (see #13 ) and when I had a look at the output for `.var_names_make_unique`, I questioned how gene names impacts on us trying to organise our cell id....any clarification would be appreciated!
Thanks!!
