### ISSUE TITLE
Mention velociraptor package

### ISSUE THREAD

**Issue by friedue** [basilkhuder/Seurat-to-RNA-Velocity#7]
Hi Basil,
great tutorial! Since you've been moving back and forth in R and python, I just wanted to add that the Bioconductor package [velociraptor](https://bioconductor.org/packages/release/bioc/vignettes/velociraptor/inst/doc/userguide.html) allows to access the scVelo functionalities from within R, which allows the user to stay with R the whole time.

**Comment by basilkhuder** [comment]
Hi @friedue, thanks so much for the recommendation! I'll be sure to look into it and add it to the tutorial.
